create table if not exists public.holder_snapshots (
  id bigint generated by default as identity primary key,
  captured_at timestamptz not null default now(),
  kas_price_usd numeric,
  total_1_plus bigint,
  a_1k_plus bigint,
  a_10k_plus bigint,
  a_100k_plus bigint,
  a_1m_plus bigint,
  a_10m_plus bigint,
  a_100m_plus bigint,
  top10_share numeric,
  top100_share numeric,
  top1000_share numeric,
  circulating numeric
);

create index if not exists holder_snapshots_captured_at_idx
  on public.holder_snapshots(captured_at);

alter table public.holder_snapshots enable row level security;

-- The browser never queries this table directly in this app.
-- Only the Next.js server uses a Supabase secret key.
revoke all on table public.holder_snapshots from anon, authenticated;
grant select, insert on table public.holder_snapshots to service_role;
