create table if not exists public.holder_snapshots (
  id bigint generated by default as identity primary key,
  captured_at timestamptz not null default now(),
  kas_price_usd numeric,
  total_1_plus bigint,
  a_1k_plus bigint,
  a_10k_plus bigint,
  a_100k_plus bigint,
  a_1m_plus bigint,
  a_10m_plus bigint,
  a_100m_plus bigint,
  top10_share numeric,
  top100_share numeric,
  top1000_share numeric,
  circulating numeric
);

create index if not exists holder_snapshots_captured_at_idx
  on public.holder_snapshots(captured_at);

-- Keep the newest row if this schema is applied to an existing database.
with ranked as (
  select id,row_number() over (
    partition by ((captured_at at time zone 'Asia/Tokyo')::date)
    order by captured_at desc,id desc
  ) as row_number
  from public.holder_snapshots
)
delete from public.holder_snapshots
where id in (select id from ranked where row_number>1);

-- Application checks improve the response, while this index closes race conditions.
create unique index if not exists holder_snapshots_jst_day_uidx
  on public.holder_snapshots (((captured_at at time zone 'Asia/Tokyo')::date));

alter table public.holder_snapshots enable row level security;

-- The browser never queries this table directly in this app.
-- Only the Next.js server uses a Supabase secret key.
revoke all on table public.holder_snapshots from anon, authenticated;
grant select, insert, delete on table public.holder_snapshots to service_role;
